<a href="https://colab.research.google.com/github/swflora/mulcamp34/blob/main/240103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#_*_coning: utf-8 _*_

import numpy as np
def main() :
  print(np.__version__)
  print("hello 가상환경")

if __name__ == "__main__" :
  main()

jupyter lab



SyntaxError: ignored

## Numpy
선형 대수, 행렬 수치 연산과 관련된 라이브러리

Numpy 기반 -> 통계, 머신러닝등을 학습


In [4]:
import numpy as np #Numpy 라이브러리를 불러오기

print(np.__version__)

1.23.5


In [5]:
num1 = [1,2,3,4]
num2 = [3,4,5,6]

num1 + num2

[1, 2, 3, 4, 3, 4, 5, 6]

In [6]:
arr1 = np.array(num1)
arr2 = np.array(num2)
arr1

array([1, 2, 3, 4])

In [7]:
arr1 + arr2

array([ 4,  6,  8, 10])

In [8]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [9]:
a1.dtype # Python -> int, Numpy -> int8, int16, int32, int64
# 메모리 관리를 위해

dtype('int64')

In [10]:
np.array([0.5,2,0.01,8]).dtype

dtype('float64')

## Numpy 배열 생성
1차원,2차원,3차원,.. 배열 생성

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10) # 1차원, 2차원, 3차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.arange(12).reshape(4,5)  # arange의 사이즈를 초과하게는 만들지 못함

ValueError: ignored

In [17]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
b2 = np.arange(5) # 1차원 배열
b2.shape

(5,)

### 배열 생성
범위의 시작과 끝 정하기

In [19]:
np.linspace(0,10,5) # 0과 10사이에 숫자가 5개가 들어가게 생성
# 균등하게 생성됨

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.linspace(0,np.pi,20) # np.pi는 pi(3.14)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## 단위 행렬

In [25]:
arr_I = np.eye(3)
arr_I # 대각선으로 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.array(['1.5','0.62'])

array(['1.5', '0.62'], dtype='<U4')

In [27]:
# astype() 데이터 형 변환 시 사용
arr = np.array(['1.5', '0.62'])
num_arr = arr.astype(float)
num_arr.dtype

dtype('float64')

In [28]:
num_f1 = np.array([10,21,0.549, 4.75, 5.98])
num_f1 = num_f1.astype(int)
num_f1  # int 형태는 값이 유실 됨

array([10, 21,  0,  4,  5])

## 난수 무작위, p.224
무작위로 숫자를 추출

In [29]:
np.random.rand(2,3) # 0에서 1사이에 실수 난수를 가짐
# 괄호 안은 배열의 범위가 아니라 배열의 크기

array([[0.57633547, 0.03169943, 0.85231129],
       [0.09635897, 0.22000725, 0.61063619]])

In [30]:
np.random.randint(2,10) # 범위를 주고 그 사이에 랜덤 숫자 생성

8

In [31]:
np.random.randint(1,100,10)

array([25, 64, 64, 53, 36, 34, 47, 60, 86, 70])

In [38]:
# 복권 숫자 자판기 (랜덤하나 중복되지 않을 것)
numbers = np.arange(101)

numbers = np.random.choice(numbers, size = 7, replace = False)
print(numbers)


[96 74 90 54  5  6 73]


numpy.random.choice 함수는 주어진 배열 또는 정수 중에서 무작위로 샘플을 추출하는 데 사용됩니다. 이 함수는 다음과 같은 형식을 가지고 있습니다:


code : numpy.random.choice(a, size=None, replace=True, p=None)
여기서 각 매개변수는 다음을 의미합니다:

a: 샘플링할 배열 또는 정수. 배열이면 배열의 원소 중에서, 정수이면 0부터 그 정수까지의 범위에서 샘플링됩니다.

size: 샘플의 크기를 지정합니다. 기본값은 None으로, 하나의 샘플을 반환합니다.

replace: 기본값은 True이며, True로 설정하면 같은 원소를 여러 번 샘플링할 수 있습니다. False로 설정하면 중복이 허용되지 않아서 배열의 길이보다 큰 샘플 크기를 요청하면 오류가 발생합니다.

p: 각 원소가 선택될 확률을 나타내는 선택 확률 배열입니다. 선택되지 않으면 모든 원소가 동일한 확률로 선택됩니다.

## 배열의 연산 , p.225


In [39]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

print(arr1 + arr2)  # 덧셈
print(arr1 - arr2)  # 뺄셈
print(arr1 * arr2)  # 곱셈
print(arr1 / arr2)  # 나눗셈


[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


### 비교 연산

In [40]:
arr1 > 20

array([False, False,  True,  True])

### 통계 연산
Numpy, 합, 평균, 표준 편차, 분산, 최솟값, 최댓값, 누적합, 누적곱 메서드가 존재한다. -> 기술 통계량

통계 : 평균이 전부
- 모수 통계
- 비모수 통계
- 베이지안 통계

In [41]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [44]:
print(arr3.sum())
print(arr3.mean())
print(arr3.std())  # 표준편차
print(arr3.var()) # 분산

10
2.0
1.4142135623730951
2.0


### 누적합과 누적곱
cumsum() : 누적합

cumprod() : 누적곱

In [47]:
arr4 = np.arange(1,5)
print(arr4.cumsum())
print(arr4.cumprod())

[ 1  3  6 10]
[ 1  2  6 24]


### 행렬 연산
선형 대수(linear algebra)를 위한 2차원 배열 연산도 지원

p.229, 행렬곱, 전치행렬, 역행렬, 행렬식 사용 예시

In [53]:
A = np.array([0,1,2,3]).reshape(2,2)
B = np.array([3,2,0,1]).reshape(2,2)
print(A)
print(B)

A.dot(B)

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]


array([[0, 1],
       [6, 7]])

In [55]:
print(A.transpose()) #전치 행렬
np.linalg.inv(A) #역행렬

[[0 2]
 [1 3]]


array([[-1.5,  0.5],
       [ 1. ,  0. ]])

## 배열의 인덱싱과 슬라이싱 , p.230
string, list, tuple과 동일한 방법으로 접근

In [58]:
a1 = np.array([0,10,20,30,40,50])

# 50을 70으로 변경하고 싶음
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [60]:
# 리스트 통해서 추출, 인덱스 위치를 리스트화해 추출
a1[[0,2,4]]

array([ 0, 20, 40])

In [61]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [63]:
print(a2[2,2]) #2열2행
print(a2[1,1]) #1열1행

90
50


In [66]:
# 90을 95로 변경
a2[2,2] = 95
a2[0] = [1,2,3] #리스트 형태로 삽입해도 에러 발생X
print(a2)

a2[0] = [1,2,3,4]
print(a2)

[[ 1  2  3]
 [40 50 60]
 [70 80 95]]


ValueError: ignored

In [68]:
a2[0] = np.array([4,5,6,7])
a2

ValueError: ignored

2차원 배열의 행과 열 위치 지정해서 원소 추출

  +(행의 위치1, 열의 위치1)(행의 위치2, 열의 위치2)



In [74]:
a2[0] = [4,5,6]
print(a2)
print(a2[[0,2],[0,1]]) # a2[0,0], a2[2,1]로 계산됨
print(a2[0,2], a2[0,1]) #0행2열, 0행1열


[[ 4  5  6]
 [40 50 60]
 [70 80 95]]
[ 4 80]
6 5


## 배열 조건문
pandas 문법과 유사

In [75]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [78]:
a[a>3]

array([4, 5, 6])

In [79]:
a % 2 == 0

array([False,  True, False,  True, False,  True])

### 배열의 슬라이싱, p.234
슬라이싱을 이용해 다양하게 데이터를 추출 가능

In [80]:
b1 = np.array([0,1,2,3,4,5])
b1[1:4]

array([1, 2, 3])

In [83]:
print(b1[:3])
print(b1[2:])
print(b1[0:4:2])

[0 1 2]
[2 3 4 5]
[0 2]


In [85]:
b1[2:5] = np.array([25,35,45])
print(b1)

b1[3:6] = 60
print(b1)

[ 0  1 25 35 45  5]
[ 0  1 25 60 60 60]


In [88]:
b2 = np.arange(10,100,10).reshape(3,3)
print(b2)

print(b2[1:3,1:3])  #1행의 3열까지, 또 1행아래의 3열까지
print(b2[1:, 1:])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[50 60]
 [80 90]]


In [92]:
print(b2[1])
print(b2[1][1:3]) #중첩가능

[40 50 60]
[50 60]


## Numpy 조건문
np.where : 단일 조건문

np.select : 다중 조건문

In [93]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
# 0, 1, 2, 3, 4, 50, 60, 70, 80, 90을 생성
np.where(arr < 5, arr, arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [95]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
# 100,101, 2,3,4,5, 12, 14,16, 18
# 2미만일 경우 100을 더하고 5초과 9이하는 곱하기 2
# 조건식과 대응되는 결과를 리스트로 생성

cond_list = [arr >5, arr <2]
choice_list = [arr *2, arr + 100]

np.select(cond_list, choice_list, default = arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## Numpy 수치연산
가장 기초적인 라이브러리

